version: "3.8"

x-common-variables: &common-variables
  SQLALCHEMY_DATABASE_URL: $SQLALCHEMY_DATABASE_URL

services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./frontend
      args:
        vite_api_base_url: $VITE_API_BASE_URL
    ports:
      - "3000:80"
    labels:
      - "traefik.http.routers.frontend.rule=Host(`mngt.docker.localhost`,`mngt.daroka.kchusap.com`, `cs3560.kchusap.com`)"

  api:
    build:
      dockerfile: Dockerfile
      context: ./backend
    ports:
      - "3001:80"
    environment:
      <<: *common-variables
    labels:
      - "traefik.http.routers.backend.rule=Host(`mngt.docker.localhost`,`mngt.daroka.kchusap.com`, `cs3560.kchusap.com`) && Path(`/api`)"
    depends_on:
      - "db"

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - pg-db-data:/var/lib/postgresql/data

volumes:
  pg-db-data: