version: '3.8'

x-common-variables: &common-variables
  MYSQL_DATABASE: books
  MYSQL_USER: MYSQL_USER
  MYSQL_PASSWORD: MYSQL_PASSWORD

services:

  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./frontend
    ports:
      - "3000:80"